### ISSUE TITLE
NDK版本有要求么？编译报错了

### ISSUE THREAD

**Issue by PopFisher** [huzongyao/FaceMorphMe#1]
F:/android-ndk-r21/build//../build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.

**Comment by huzongyao** [comment]
更新gradle版本解决了，拉取最新代码即可

**Comment by PopFisher** [comment]
是我的问题，我拷贝opencv库的时候，没有去看gitignore里面的目录，没有拷贝第三方库进去
